### ISSUE TITLE
Check to see if we can make links to relative docs work in github and website

### ISSUE THREAD

**Issue by marcpalmer** [MontanaFlossCo/Flint-Documentation#4]
Links to `activities` don't work in github, but they do if they are `activities.md`. The question is does this still work when building the flint.tools site with this content? See #3

**Comment by marcpalmer** [comment]
@freak4pc I have investigated and I think I have a solution. Just deploying new site and then re-testing with a guide doc updated on github.

**Comment by marcpalmer** [comment]
OK @freak4pc this is now done. Thanks for the prod. All internal doc links updated to work on github, site still builds from these... also fixed bugs in the "Related Articles" logic of the site and improved the tags

**Comment by freak4pc** [comment]
Thanks for the prompt fix !
